export const fields = [
  {
    label: "Applicant's Name",
    formControlName: 'title',
    placeholder: "Enter Applicant's Name",
    type: 'text',
    errorMessages: { required: "Applicant's Name is required" },
    isMandatory: true,
  },
  {
    label: "Father's Name",
    formControlName: 'fatherName',
    placeholder: "Enter Father's Name",
    type: 'text',
    errorMessages: { required: "Father's Name is required" },
    isMandatory: true,
  },
  {
    label: 'PAN Number',
    formControlName: 'panNumber',
    placeholder: 'AAABB1234C',
    type: 'text',
    errorMessages: {
      required: 'PAN Number is required',
      minlength: 'PAN must be of 10 characters',
    },
    isMandatory: true,
  },
  {
    label: 'Date of Birth',
    formControlName: 'dateOfBirth',
    placeholder: '',
    type: 'date',
    errorMessages: { required: 'Date of Birth is required' },
    isMandatory: true,
  },
  {
    label: 'Aadhar Card Number',
    formControlName: 'aadharCard',
    placeholder: '999955551111',
    type: 'number',
    errorMessages: {
      required: 'Aadhar Card Number is required',
      maxlength: 'Please enter a valid Aadhar Card Number',
    },
    isMandatory: true,
  },
  {
    label: 'Mobile Number',
    formControlName: 'mobileNo',
    placeholder: '1234567891',
    type: 'number',
    errorMessages: { required: 'Mobile Number is required' },
    isMandatory: true,
  },
  {
    label: 'VLE Mobile',
    formControlName: 'vleMobile',
    placeholder: '1234567891',
    type: 'number',
    errorMessages: {},
    isMandatory: false,
  },
  {
    label: 'Email Id',
    formControlName: 'emailId',
    placeholder: 'youremail@gmail.com',
    type: 'email',
    errorMessages: {
      required: 'Email Id is required',
      email: 'Please enter a valid email',
    },
    isMandatory: true,
  },
  {
    label: 'Address',
    formControlName: 'address',
    placeholder: "Enter Applicant's Residential Address",
    type: 'text',
    errorMessages: { required: 'Address is required' },
    isMandatory: true,
  },
];
